export const ONLINE_PRESENCE_TTL_MS = 30_000;
export const ONLINE_CHALLENGE_TTL_MS = 30_000;
export const ONLINE_INITIAL_CLOCK_MS = 600_000;
export const ONLINE_INITIAL_MAGIC_COINS = 500;
export const ONLINE_MAX_DRAW_OFFERS_PER_PLAYER = 3;
